### ISSUE TITLE
Bug in README

### ISSUE THREAD

**Issue by Artaud** [ap-automator/jekyll-rushed-analytics#21]
There's a bug in the readme, stating that you should configure this gem with ```jekyll-rushed-analytics``` property in the _config.yml, but actually it should be ```jekyll_rushed_analytics```, according to https://github.com/ap-automator/jekyll-rushed-analytics/blob/master/lib/jekyll-rushed-analytics.rb

Will provide a PR in a few

**Comment by Artaud** [comment]
Here goes https://github.com/ap-automator/jekyll-rushed-analytics/pull/22

**Comment by Artaud** [comment]
Actually, are documentation mistakes called bugs?

**Comment by sukrosono** [comment]
Thanks, I think it poorly documented.
But it create bug basically, have a nice day :)
